### ISSUE TITLE
听歌排行的喜欢和下载按钮没有垂直居中

### ISSUE THREAD

**Issue by LKZD7** [mo-jinran/What-is-the-cover-of-this-music#9]
![QQ截图20230224010228](https://user-images.githubusercontent.com/33388137/220977796-3924d731-0121-4153-a686-30277476c684.png)

刚打开网易云，直接打开听歌排行是正常的，但是再切换到别的页面之后（比如我的喜欢或者别的歌单），再看听过排行就变成如图所示的样子了。

**Comment by mo-jinran** [comment]
这是安装了第三方主题了吧，具体插件名称是什么

**Comment by LKZD7** [comment]
对，主题名叫Material You

**Comment by cale044** [comment]
> 对，主题名叫Material You
@solstice23
